name: ical24
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.0.0
  http: ^1.0.0
  ical: ^0.2.2
  intl: ^0.17.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  timezone: ^0.9.2

dev_dependencies:
  lint: ^2.1.2
  lints: ^2.0.0
  test: ^1.15.0
