name: ical24
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.5
  ical: ^0.2.2
  intl: ^0.17.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0

dev_dependencies:
  lint: ^1.10.0
  lints: ^2.0.0
  test: ^1.15.0
